---
title: "Ashley_HealthData"
author: "Ashley Weaver"
date: "5/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r pre_process_race}

library(dplyr)
library(ggplot2)
library(tidyr)

hdat <- read.csv("R11371317_SL050.csv")
racedat <- read.csv("cc-est2018-alldata-22.csv")

racedat1 <- racedat %>% 
  filter(YEAR == 9,
         AGEGRP == 0) %>% 
  group_by(COUNTY) %>% 
  mutate(White = sum(WA_MALE, WA_FEMALE),
         Minority = TOT_POP - White,
         Perc_White = (White / TOT_POP) * 100,
         Perc_Minority = (Minority / TOT_POP) * 100) %>% 
  ungroup() %>% 
  select(STNAME, CTYNAME, TOT_POP, White, 
         Minority, Perc_White, Perc_Minority) %>% 
  mutate(LA_POP = sum(TOT_POP),
         LA_White_Perc = mean(Perc_White))

racedat2 <- racedat1 %>% 
  select(LA_White_Perc, STNAME) %>%
  pivot_wider(values_from = LA_White_Perc, names_from = STNAME) %>% 
  pivot_longer(values_to = "White", names_to = "Louisiana", cols = 1)

racedat2 <- racedat1 %>% 
  select(LA_White_Perc, STNAME) %>%
  pivot_wider(values_from = LA_White_Perc, names_from = STNAME) %>% 
  pivot_longer(values_to = "Value", names_to = "White", cols = 1)

CAracedat1 <- racedat1  %>% 
           filter(CTYNAME %in% c("East Baton Rouge Parish", 
                                "West Baton Rouge Parish",
                                "Ascension Parish",
                                "St. John the Baptist Parish",
                                "Iberville Parish",
                                "St. Charles Parish",
                                "Jefferson Parish",
                                "Orleans Parish"))
```
